spring:
  application:
    name: hotel
  datasource:
    url: jdbc:postgresql://localhost:5454/hotel_db
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      resource:
        jwt:
          issuer-uri: http://localhost:9001/realms/hotel-booking

server:
  port: 8089

keycloak:
  admin:
    client-id: user-provisioning-client
    client-secret: OmlvRRMQpn1R0fagVgI3olZHal6DWHC1
    realm: hotel-booking
    server-url: http://localhost:9001